### PR TITLE
Prevent AP setup with too short password

### LINKED ISSUE #15: Do not crash on WiFi passwords shorter than 8 characters
It's been reported (in this PR https://github.com/bitcraze/crazyflie-firmware/pull/1072) that we're not handling WiFi passwords shorter than 8 characters gracefully (we should not try to connect with passwords shorter than 8 characters). This should be fixed so we do not try to connect unless we have a long enough password.

### PR DESCRIPTION
**Pull request by gemenerik**
This PR ensures that the firmware does not attempt to set up an access point if the configured password is shorter than 8 characters. If an invalid password is detected, a warning is logged to inform the user (visible in cfclient console), and the AP setup is skipped.

Fixes #15

### CODE REVIEW

File: main/wifi.c [hunk 1]
```diff
@@ -235,8 +235,12 @@ static void wifi_ctrl(void* _param) {
           if (rxp.data[1] == 0) {
             wifi_init_sta(ssid, key);
           } else {
-            wifi_init_softap(ssid, key);
-          }          
+            if (strlen(key) < 8) {
```
Comment (ToveRumar) [inline main/wifi.c:238]: If we only check the length so it must be longer than 7, we can never set up an AP with open security. 

Inside the wifi_init_softap() the authentication mode is set to open if the password is longer than 0. 
I would say we should check the invalid range. 
```suggestion
            if (0 < strlen(key) && strlen(key) < 8) {
```

Comment (gemenerik) [reply main/wifi.c]: Implemented and tested your suggestion
